### ekf config file ###
ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    # The frequency, in Hz, at which the filter will output a position estimate. Note that the filter will not begin
    # computation until it receives at least one message from one of the inputs. It will then run continuously at the
    # frequency specified here, regardless of whether it receives more measurements. Defaults to 30 if unspecified.
    frequency: 50.0
    sensor_timeout: 0.1

    # ekf_localization_node and ukf_localization_node both use a 3D omnidirectional motion model. If this parameter is
    # set to true, no 3D information will be used in your state estimate. Use this if you are operating in a planar
    # environment and want to ignore the effect of small variations in the ground plane that might otherwise be detected
    # by, for example, an IMU. Defaults to false if unspecified.
    two_d_mode: true

    # Whether to publish the acceleration state. Defaults to false if unspecified.
    publish_acceleration: false
    # Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
    publish_tf: true
    map_frame_id: map              # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_footprint  # Defaults to "base_link" if unspecified
    world_frame: odom
    transform_time_offset: 0.0
    debug: true

    pose0: rtabmap/localization_pose
    pose0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    # The filter accepts an arbitrary number of inputs from each input message type (nav_msgs/Odometry,
    # geometry_msgs/PoseWithCovarianceStamped, geometry_msgs/TwistWithCovarianceStamped,
    # sensor_msgs/Imu). To add an input, simply append the next number in the sequence to its "base" name, e.g., odom0,
    # odom1, twist0, twist1, imu0, imu1, imu2, etc. The value should be the topic name. These parameters obviously have no
    # default values, and must be specified.

    odom0: /diff_cont/odom
    odom0_config : [true, true, false,     # position (x, y, z), easy to drift so don't use it
                    false, false, false,      # orientation (roll, pitch, yaw)
                    false, false, false,       # linear velocity (vx, vy, vz)
                    false, false, false,      # angular velocity (vroll, vpitch, vyaw)
                    false, false, false]     # ax, ay, az
    # [ADVANCED] When measuring one pose variable with two sensors, a situation can arise in which both sensors under-
    # report their covariances. This can lead to the filter rapidly jumping back and forth between each measurement as they
    # arrive. In these cases, it often makes sense to (a) correct the measurement covariances, or (b) if velocity is also
    # measured by one of the sensors, let one sensor measure pose, and the other velocity. However, doing (a) or (b) isn't
    # always feasible, and so we expose the differential parameter. When differential mode is enabled, all absolute pose
    # data is converted to velocity data by differentiating the absolute pose measurements. These velocities are then
    # integrated as usual. NOTE: this only applies to sensors that provide pose measurements; setting differential to true
    # for twist measurements has no effect.

    twist0: /diff_cont/cmd_vel_unstamped
    twist0_config: [false, false, false,
                    false, false, false,
                    true, true, false,
                    false, false, true,
                    false, false, false]

    imu0_config : [false, false, false,    # x, y, z position
                   false, false, true,     # roll, pitch, yaw
                   false, false, false,    # vx, vy, vz
                   false, false, true,     # vroll, vpitch, vyaw
                   true, false, false]     # ax, ay, az

    odom0_differential: false
    twist0_differential: false
    imu0_differential: false

    odom0_relative: true
    twist0_relative: true
    imu0_relative: true

    odom0_queue_size: 5
    twist0_queue_size: 10
    imu0_queue_size: 50

    imu_remove_gravitational_acceleration: True

    # the values are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    process_noise_covariance: [
      0.05,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.05,  0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.06,  0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.03,  0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.03,  0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.06,  0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.025,  0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.025,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.04,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.01,  0.0,   0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.01,  0.0,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.1,  0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.01,  0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.01,  0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.015
    ]

    # The values are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    initial_estimate_covariance: [
      1e-9,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   1e-9,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   1e-9,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   1e-9,  0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   1e-9,  0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   5e-10,  0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-9,  0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-9,  0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-9,  0.0,    0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   1e-9,   0.0,    0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    1e-9,   0.0,    0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    1e-9,   0.0,   0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    1e-9,  0.0,   0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   1e-9,  0.0,
      0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,   0.0,    0.0,    0.0,    0.0,   0.0,   1e-9
    ]

